In [33]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

Create a 1D NumPy array containing numbers from 1 to 20.

In [34]:
data = np.arange(1,21)
print(data)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Create a NumPy array of all even numbers between 10 and 50

In [35]:
arr= np.arange(10,50)
print(arr[arr % 2 == 0])

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


Create a 3×3 NumPy array filled with zeros.

In [36]:
a= np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Create a 4×4 identity matrix.

In [37]:
b = np.eye(4,4)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Generate a NumPy array of 10 random integers between 1 and 100.

In [38]:
c= np.random.randint(1,100,10)
print(c)

[92 61 71 19 52 84 13 16 70 47]


From a given array, extract the first 5 elements

In [39]:
d= np.arange(1,10)
print(d[1:6])

[2 3 4 5 6]


Reverse a NumPy array using slicing.

In [40]:
e= np.arange(20,57)
print(e[::-1])

[56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33
 32 31 30 29 28 27 26 25 24 23 22 21 20]


Reshape a 1D array of size 12 into a 3×4 matrix.

In [41]:
f = np.arange(0,12).reshape(3,4)
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Find the shape, size, and number of dimensions of an array.

In [42]:
print(np.size(f))

12


In [43]:
print(np.shape(f))

(3, 4)


In [44]:
print(np.ndim(f))

2


Replace all values greater than 50 in an array with 50.

In [45]:
h= np.random.randint(20,90,15)
print(np.where(h >50 , 50, h))

[20 50 50 44 34 50 50 50 50 50 50 50 50 50 50]


Perform element-wise addition, subtraction, multiplication, and division on two arrays.

In [46]:
abs= np.array([2,3,4])
bs= np.array([6,7,8])
print(abs+bs)
print(abs-bs)
print(abs*bs)
print(abs/bs)

[ 8 10 12]
[-4 -4 -4]
[12 21 32]
[0.33333333 0.42857143 0.5       ]


Find the mean, median, and standard deviation of an array.

In [47]:
np.mean(f)

np.float64(5.5)

In [48]:
np.median(f)

np.float64(5.5)

In [49]:
np.std(f)

np.float64(3.452052529534663)

Compute the sum of each row in a 2D array.

In [50]:
np.sum(f,axis=1)

array([ 6, 22, 38])

Normalize an array so that values lie between 0 and 1.

In [51]:
array= np.array([2,3,4,5,6,7,6,7,2,4,4,5,6,6,74,33,5,56])
min= np.min(array)
print(min)
max= np.max(array)
print(max)
normalization = (array-min)/(max-min)
print(normalization)

2
74
[0.         0.01388889 0.02777778 0.04166667 0.05555556 0.06944444
 0.05555556 0.06944444 0.         0.02777778 0.02777778 0.04166667
 0.05555556 0.05555556 1.         0.43055556 0.04166667 0.75      ]


Find the maximum and minimum values along each column.

In [52]:
np.min(f,axis=0)

array([0, 1, 2, 3])

In [53]:
np.max(f,axis=0)

array([ 8,  9, 10, 11])

Extract all values greater than the average of the array.

In [59]:
n=np.mean(f)
print(n)
print(f[f>n])

5.5
[ 6  7  8  9 10 11]


Count how many elements in an array are divisible by 3.

In [65]:
h= f%3==0
print(h)
np.sum(h)

[[ True False False  True]
 [False False  True False]
 [False  True False False]]


np.int64(4)

Replace all odd numbers in an array with -1.

In [66]:
np.where ( f % 2 != 0,-1,f)

array([[ 0, -1,  2, -1],
       [ 4, -1,  6, -1],
       [ 8, -1, 10, -1]])

Find the indices of elements where values are greater than 75.

In [72]:
l= np.random.randint(23,98,34)
print(l)
np.where(l>75)

[49 75 96 97 63 95 72 41 71 88 79 25 65 89 43 71 88 73 39 77 71 62 78 32
 32 54 70 78 73 34 34 84 58 46]


(array([ 2,  3,  5,  9, 10, 13, 16, 19, 22, 27, 31]),)

Check if two NumPy arrays are equal element-wise.

In [75]:
ihd= np.array([2,3,44,5,6,22])
j=np.array([2,3,4,4,4,5])
print(ihd==j)

[ True  True False False False False]
